// REAL Firebase config for project `campus-f4748` (committed on purpose —
// since 2026-07-21, when the Firebase project went live).
//
// This file is GENERATED by the FlutterFire CLI — regenerate, don't hand-edit:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=campus-f4748
//
// Committing these values is fine by design: Firebase app config
// (apiKey/appId/projectId) is public client configuration and holds no server
// secrets. Access control lives entirely in Firestore security rules
// (`firestore.rules`: public read, client writes blocked), not in hiding
// these ids.
//
// BUT the platform config files ARE gitignored:
// `android/app/google-services.json` / `ios/Runner/GoogleService-Info.plist`.
// A fresh checkout must re-fetch them before building, e.g.:
//
//   firebase apps:sdkconfig android <appId> --project campus-f4748 \
//     --out android/app/google-services.json
//
// Careful: any run with `--dart-define=USE_FIRESTORE=true` (or the per-feature
// USE_FIRESTORE_CALENDAR / USE_FIRESTORE_DINING flags) connects to the
// PRODUCTION Firestore of `campus-f4748`.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Campus-On targets iOS + Android only; web is out of scope for MVP.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'No Firebase options for $defaultTargetPlatform. '
          'Run `flutterfire configure` to regenerate this file.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB16BfoVwCYzlnmiDWyi0wTXiW7LytLXC0',
    appId: '1:1051782345606:android:5fa919e3aa697de1b57207',
    messagingSenderId: '1051782345606',
    projectId: 'campus-f4748',
    storageBucket: 'campus-f4748.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARb5TTKHa4s9hQQqcRxafLuwt1YVwmDhY',
    appId: '1:1051782345606:ios:fb4193d1c1301929b57207',
    messagingSenderId: '1051782345606',
    projectId: 'campus-f4748',
    storageBucket: 'campus-f4748.firebasestorage.app',
    iosBundleId: 'io.github.ljw092601.campuson',
  );
}
