// PLACEHOLDER — NOT REAL CREDENTIALS.
//
// This file is normally GENERATED by the FlutterFire CLI and should be
// regenerated (not hand-edited) once a Firebase project exists:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=campus-on-<your-project-id>
//
// That command overwrites this file with the real per-platform options AND
// drops `android/app/google-services.json` + `ios/Runner/GoogleService-Info.plist`.
// Those files hold no server secrets (Firebase app config is public by design);
// access is gated by Firestore security rules (`firestore.rules`), not by hiding
// these ids. Even so, they are per-project config and should come from
// `flutterfire configure`, never be copied from another project.
//
// The values below are obvious placeholders so an accidental
// `--dart-define=USE_FIRESTORE=true` run fails fast at Firebase.initializeApp
// instead of silently pointing at the wrong project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Campus-On targets iOS + Android only; web is out of scope for MVP.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'No Firebase options for $defaultTargetPlatform. '
          'Run `flutterfire configure` to regenerate this file.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB16BfoVwCYzlnmiDWyi0wTXiW7LytLXC0',
    appId: '1:1051782345606:android:5fa919e3aa697de1b57207',
    messagingSenderId: '1051782345606',
    projectId: 'campus-f4748',
    storageBucket: 'campus-f4748.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARb5TTKHa4s9hQQqcRxafLuwt1YVwmDhY',
    appId: '1:1051782345606:ios:fb4193d1c1301929b57207',
    messagingSenderId: '1051782345606',
    projectId: 'campus-f4748',
    storageBucket: 'campus-f4748.firebasestorage.app',
    iosBundleId: 'io.github.ljw092601.campuson',
  );
}
