import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart' show debugPrint, visibleForTesting;

import '../../domain/entities/academic_event.dart';
import '../../domain/entities/admin_guide.dart';
import '../../domain/entities/building_floors.dart';
import '../../domain/entities/dining_menu.dart';
import '../../domain/entities/facility.dart';

/// Single source of truth for Firestore collection names + document→entity
/// mapping. Keeping the mapping here (not in the entities) means the domain
/// layer stays framework-free: entities know only `fromJson` with the UX §8
/// field names; this file bridges Firestore quirks (doc id, Timestamp) onto
/// that JSON shape.
class FirestorePaths {
  const FirestorePaths._();

  /// One document per facility. Document id == [Facility.id].
  static const String facilities = 'facilities';

  /// One document per admin-guide item. Document id == [AdminGuideItem.id].
  static const String guideItems = 'guide_items';

  /// One document per building's floor guide. Document id == [Facility.id].
  static const String buildingFloors = 'building_floors';

  /// One document per academic-calendar event. Document id == immutable
  /// event id generated by the admin sheet (design doc §7).
  static const String academicEvents = 'academic_events';

  /// Static cafeteria info (names, hours, campus, facility link).
  /// Document id == [CafeteriaMenu.id] (e.g. `seunghak-student`).
  static const String cafeterias = 'cafeterias';

  /// One document per cafeteria per day. Document id ==
  /// `<cafeteriaId>_<yyyy-MM-dd>`; fields: cafeteriaId, date, status, meals.
  static const String diningMenus = 'dining_menus';
}

/// Normalizes a raw Firestore document map onto the JSON shape the entity
/// `fromJson` expects:
///  - injects `id` from the document id (schema stores id as the doc key),
///  - converts Firestore [Timestamp] `updatedAt` into an ISO-8601 string
///    (the entity parses it with `DateTime.tryParse`).
Map<String, dynamic> _normalize(
  DocumentSnapshot<Map<String, dynamic>> doc,
) {
  final data = <String, dynamic>{...?doc.data()};
  data['id'] = doc.id;
  final ts = data['updatedAt'];
  if (ts is Timestamp) {
    data['updatedAt'] = ts.toDate().toIso8601String();
  }
  return data;
}

/// Maps [docs] to entities, skipping (and logging) any document whose mapping
/// throws — one malformed admin write must not blank the whole list. Same
/// policy as `FirestoreAcademicCalendarRepository`'s per-document skip;
/// [collection] only labels the log line.
List<T> mapDocsSkippingMalformed<T>(
  Iterable<DocumentSnapshot<Map<String, dynamic>>> docs,
  String collection,
  T Function(DocumentSnapshot<Map<String, dynamic>>) fromDoc,
) {
  final out = <T>[];
  for (final doc in docs) {
    try {
      out.add(fromDoc(doc));
    } catch (e) {
      debugPrint('$collection/${doc.id}: skipped malformed doc ($e)');
    }
  }
  return out;
}

Facility facilityFromDoc(DocumentSnapshot<Map<String, dynamic>> doc) =>
    Facility.fromJson(_normalize(doc));

AdminGuideItem guideFromDoc(DocumentSnapshot<Map<String, dynamic>> doc) =>
    AdminGuideItem.fromJson(_normalize(doc));

BuildingFloors buildingFloorsFromDoc(
        DocumentSnapshot<Map<String, dynamic>> doc) =>
    // `_normalize` injects the doc id as `id`; the entity reads it as
    // `facilityId` (doc id == owning facility id by schema).
    BuildingFloors.fromJson(_normalize(doc));

AcademicEvent academicEventFromDoc(
        DocumentSnapshot<Map<String, dynamic>> doc) =>
    AcademicEvent.fromJson(_normalize(doc));

/// Coerces a raw `status` field to one of the three values the design doc §7
/// allows (`open`/`closed`/`unpublished`). Anything else — missing, a typo,
/// a wrong type — becomes `unpublished`: an admin's broken input must never
/// read as "open", nor fall through to the entity's legacy empty-meals==closed
/// rule and get announced as a closure (D1). Firestore-adapter-only: the
/// legacy fallback in [CafeteriaMenu.status] stays as-is for mock data.
@visibleForTesting
String normalizeDiningStatus(Object? raw) =>
    raw == 'open' || raw == 'closed' || raw == 'unpublished'
        ? raw as String
        : 'unpublished';

/// Joins one static cafeteria doc with that day's optional menu doc
/// (design doc §7): no menu doc → `unpublished` with no meals; a doc carries
/// `status` (open/closed/unpublished) and, when open, the `meals` array.
CafeteriaMenu cafeteriaMenuFromDocs(
  DocumentSnapshot<Map<String, dynamic>> cafeteriaDoc,
  Map<String, dynamic>? menuData,
) =>
    cafeteriaMenuFromData(_normalize(cafeteriaDoc), menuData);

/// Pure core of [cafeteriaMenuFromDocs]: [cafeteria] is the already-normalized
/// cafeteria map (doc id injected as `id`). Split out so the join + status
/// normalization are unit-testable without a Firestore instance.
@visibleForTesting
CafeteriaMenu cafeteriaMenuFromData(
  Map<String, dynamic> cafeteria,
  Map<String, dynamic>? menuData,
) {
  if (menuData == null) {
    return CafeteriaMenu.fromJson(
        {...cafeteria, 'meals': const [], 'status': 'unpublished'});
  }
  return CafeteriaMenu.fromJson({
    ...cafeteria,
    'meals': menuData['meals'] ?? const [],
    'status': normalizeDiningStatus(menuData['status']),
  });
}
