import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart' show visibleForTesting;

import '../../domain/entities/academic_event.dart';
import '../../domain/entities/admin_guide.dart';
import '../../domain/entities/building_floors.dart';
import '../../domain/entities/dining_menu.dart';
import '../../domain/entities/facility.dart';
import 'repository_exceptions.dart';

/// Single source of truth for Firestore collection names + document→entity
/// mapping. Keeping the mapping here (not in the entities) means the domain
/// layer stays framework-free: entities know only `fromJson` with the UX §8
/// field names; this file bridges Firestore quirks (doc id, Timestamp) onto
/// that JSON shape.
class FirestorePaths {
  const FirestorePaths._();

  /// One document per facility. Document id == [Facility.id].
  static const String facilities = 'facilities';

  /// One document per admin-guide item. Document id == [AdminGuideItem.id].
  static const String guideItems = 'guide_items';

  /// One document per building's floor guide. Document id == [Facility.id].
  static const String buildingFloors = 'building_floors';

  /// One document per academic-calendar event. Document id == immutable
  /// event id generated by the admin sheet (design doc §7).
  static const String academicEvents = 'academic_events';

  /// Static cafeteria info, one document per cafeteria (8 as of 2026-10;
  /// managed by the admin sheet "식당" tab). Document id == [CafeteriaMenu.id]
  /// (e.g. `seunghak-student`). Fields:
  ///  - `name_ko`, `name_en` (string)
  ///  - `campus` (`seunghak|gudeok|bumin`)
  ///  - `hours` (array of `{open: "HH:mm", close: "HH:mm"}` serving windows;
  ///    the gaps between them are breaks; may be absent/empty when the school
  ///    publishes no hours — 공과대학 식당)
  ///  - `hours_ko`, `hours_en` (free-text note, e.g. "천원의아침밥 09:00부터 선착순")
  ///  - `facilityId` (map pin, optional)
  ///  - `order` (number — display order inside its campus group)
  static const String cafeterias = 'cafeterias';

  /// One document per cafeteria per day. Document id ==
  /// `<cafeteriaId>_<yyyy-MM-dd>`. Fields:
  ///  - `cafeteriaId`, `date` ("yyyy-MM-dd"), `status`
  ///    (`open|closed|unpublished`), `updatedAt` (Timestamp)
  ///  - `sections`: array of
  ///    `{slot: breakfast|lunch|dinner|allDay, kind: set|alacarte|snack|thousandWon,
  ///      price?: number, note?: string, items: [{name, price?}]}`
  ///  - legacy (pre-2026-10) documents carry `meals: [{type, items, price}]`
  ///    instead; [CafeteriaMenu.fromJson] converts those to `set` sections.
  static const String diningMenus = 'dining_menus';
}

/// Hard upper bounds for collection `list` queries (audit M-26).
///
/// Every list query the app issues must go through `readQuery` with one of
/// these, because `firestore.rules` only allows `list` when
/// `request.query.limit <= N` — an un-limited query has no `limit` field and
/// is rejected. Keep the rules' N >= the value here for the same collection
/// (`test/firestore_limits_test.dart` cross-checks the two).
///
/// Sized at roughly 5–10x the seeded data (tool/firestore_seed/*.seed.json)
/// so normal growth never truncates; when a result does fill the limit,
/// `readQuery` marks it `incomplete` so the existing partial-data banner
/// shows instead of silently dropping rows.
class FirestoreListLimits {
  const FirestoreListLimits._();

  /// Seeded: 48 facilities.
  static const int facilities = 500;

  /// Seeded: 18 guide items.
  static const int guideItems = 200;

  /// Seeded: 34 floor guides. The app only `get`s single docs here; the limit
  /// exists so the rules' `list` bound has a matching app-side constant.
  static const int buildingFloors = 200;

  /// Seeded: 14 events per academic year; the collection accumulates across
  /// years, so leave the most headroom here.
  static const int academicEvents = 500;

  /// Seeded: 8 cafeterias (4 승학, 3 부민, 1 구덕).
  static const int cafeterias = 50;

  /// Queried per date (`where date == yyyy-MM-dd`), so a result is at most
  /// one doc per cafeteria.
  static const int diningMenus = 50;

  /// Collection name → app-side limit, for the rules cross-check test.
  static const Map<String, int> byCollection = {
    FirestorePaths.facilities: facilities,
    FirestorePaths.guideItems: guideItems,
    FirestorePaths.buildingFloors: buildingFloors,
    FirestorePaths.academicEvents: academicEvents,
    FirestorePaths.cafeterias: cafeterias,
    FirestorePaths.diningMenus: diningMenus,
  };
}

/// Normalizes a raw Firestore document map onto the JSON shape the entity
/// `fromJson` expects:
///  - injects `id` from the document id (schema stores id as the doc key),
///  - converts Firestore [Timestamp] `updatedAt` into an ISO-8601 string
///    (the entity parses it with `DateTime.tryParse`).
Map<String, dynamic> _normalize(
  DocumentSnapshot<Map<String, dynamic>> doc,
) {
  final data = <String, dynamic>{...?doc.data()};
  data['id'] = doc.id;
  final ts = data['updatedAt'];
  if (ts is Timestamp) {
    data['updatedAt'] = ts.toDate().toIso8601String();
  }
  return data;
}

/// Maps [docs] to entities, skipping any document whose mapping throws — one
/// malformed admin write must not blank the whole list. Each skipped document
/// is recorded in [FirestoreReadLog] under [collection] (audit L-27: no
/// `debugPrint`, so the record exists in release builds too).
List<T> mapDocsSkippingMalformed<T>(
  Iterable<DocumentSnapshot<Map<String, dynamic>>> docs,
  String collection,
  T Function(DocumentSnapshot<Map<String, dynamic>>) fromDoc,
) {
  final out = <T>[];
  for (final doc in docs) {
    try {
      out.add(fromDoc(doc));
    } catch (e) {
      FirestoreReadLog.record(collection, doc.id, e);
    }
  }
  return out;
}

Facility facilityFromDoc(DocumentSnapshot<Map<String, dynamic>> doc) =>
    Facility.fromJson(_normalize(doc));

AdminGuideItem guideFromDoc(DocumentSnapshot<Map<String, dynamic>> doc) =>
    AdminGuideItem.fromJson(_normalize(doc));

BuildingFloors buildingFloorsFromDoc(
        DocumentSnapshot<Map<String, dynamic>> doc) =>
    // `_normalize` injects the doc id as `id`; the entity reads it as
    // `facilityId` (doc id == owning facility id by schema).
    BuildingFloors.fromJson(_normalize(doc));

AcademicEvent academicEventFromDoc(
        DocumentSnapshot<Map<String, dynamic>> doc) =>
    AcademicEvent.fromJson(_normalize(doc));

/// Coerces a raw `status` field to one of the three values the design doc §7
/// allows (`open`/`closed`/`unpublished`). Anything else — missing, a typo,
/// a wrong type — becomes `unpublished`: an admin's broken input must never
/// read as "open", nor fall through to the entity's legacy empty-meals==closed
/// rule and get announced as a closure (D1). Firestore-adapter-only: the
/// legacy fallback in [CafeteriaMenu.status] stays as-is for mock data.
@visibleForTesting
String normalizeDiningStatus(Object? raw) =>
    raw == 'open' || raw == 'closed' || raw == 'unpublished'
        ? raw as String
        : 'unpublished';

/// Joins one static cafeteria doc with that day's optional menu doc
/// (design doc §7): no menu doc → `unpublished` with no sections; a doc
/// carries `status` (open/closed/unpublished) and, when open, the `sections`
/// array (or the legacy `meals` array on pre-redesign documents).
CafeteriaMenu cafeteriaMenuFromDocs(
  DocumentSnapshot<Map<String, dynamic>> cafeteriaDoc,
  Map<String, dynamic>? menuData,
) =>
    cafeteriaMenuFromData(_normalize(cafeteriaDoc), menuData);

/// Pure core of [cafeteriaMenuFromDocs]: [cafeteria] is the already-normalized
/// cafeteria map (doc id injected as `id`). Split out so the join + status
/// normalization are unit-testable without a Firestore instance.
///
/// The menu doc's `sections` is handed to the entity untouched; a document
/// that still has only `meals` is passed through as-is too, because
/// [CafeteriaMenu.fromJson] converts legacy meals into `set` sections itself.
/// A wrong-typed `sections`/`meals` (e.g. a string) makes the entity throw,
/// which the repository turns into `unavailable`.
@visibleForTesting
CafeteriaMenu cafeteriaMenuFromData(
  Map<String, dynamic> cafeteria,
  Map<String, dynamic>? menuData,
) {
  // The static doc must never smuggle a day's menu or status into the join.
  final base = {...cafeteria}
    ..remove('sections')
    ..remove('meals')
    ..remove('status');
  if (menuData == null) {
    return CafeteriaMenu.fromJson(
        {...base, 'sections': const [], 'status': 'unpublished'});
  }
  final hasSections = menuData.containsKey('sections');
  return CafeteriaMenu.fromJson({
    ...base,
    if (hasSections)
      'sections': menuData['sections'] ?? const []
    else
      'meals': menuData['meals'] ?? const [],
    'status': normalizeDiningStatus(menuData['status']),
  });
}
